Oguz/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Oguz.Data;

namespace Oguz.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Clients()
        {
            return View();
        }

        public IEnumerable<ApplicationUser> GetAllClients()
        {
            return _context.ApplicationUsers;
        }
    }
}

Oguz/Controllers/BrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Oguz.Data;
using Oguz.Models;

namespace Oguz.Controllers
{
    public class BrandsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BrandsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Brands
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }

        // GET: Brands/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // GET: Brands/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Brands/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Brand brand)
        {
            if (ModelState.IsValid)
            {
                brand.Id = Guid.NewGuid();
                _context.Add(brand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands.FindAsync(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        // POST: Brands/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Name")] Brand brand)
        {
            if (id != brand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(brand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BrandExists(brand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        // GET: Brands/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var brand = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (brand == null)
            {
                return NotFound();
            }

            return View(brand);
        }

        // POST: Brands/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var brand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(brand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BrandExists(Guid id)
        {
            return _context.Brands.Any(e => e.Id == id);
        }
    }
}

Oguz/Controllers/ClientsController.cs
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading.Tasks;
//using Microsoft.AspNetCore.Identity;
//using Microsoft.AspNetCore.Mvc;
//using Microsoft.EntityFrameworkCore;
//using Oguz.Data;

//namespace Oguz.Controllers
//{
//    public class ClientsController : Controller
//    {

//        private readonly ApplicationDbContext _context;
//        UserManager<ApplicationUser> _userManager;

//        public ClientsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
//        {
//            _context = context;
//            _userManager = userManager;
//        }

//        public IActionResult Index() => RedirectToAction(nameof(Section));

//        public IActionResult Section() => View();

//        public async Task<IActionResult> Edit(Guid? id)
//        {
//            var order = await _userManager.FindByIdAsync(id.ToString());
//            if (id == null)
//                return NotFound();
//            if (order == null)
//                return NotFound();

//            return View(order);
//        }

//        [HttpPost]
//        [ValidateAntiForgeryToken]
//        public async Task<IActionResult> Edit(ApplicationUser user)
//        {
//            if (ModelState.IsValid)
//            {
//                try
//                {
//                    _context.ApplicationUsers.Update(user);
//                    await _context.SaveChangesAsync();
//                }
//                catch (DbUpdateConcurrencyException)
//                {
//                    if (!UserExists(user.Id))
//                    {
//                        return NotFound();
//                    }
//                    else
//                    {
//                        throw;
//                    }
//                }
//                return RedirectToAction(nameof(Index));
//            }
//            return View(user);
//        }

//        public IActionResult Delete(Guid? id)
//        {
//            var order = _context.Orders.Find(id);
//            var sizes = _context.Sizes.Where(c => c.OrderId == id);

//            _context.Sizes.RemoveRange(sizes);
//            _context.Orders.Remove(order);
//            _context.SaveChanges();
//            return RedirectToAction(nameof(Index));
//        }

//        private bool UserExists(string id)
//        {
//            throw new NotImplementedException();
//        }
//    }
//}

Oguz/Controllers/PillowController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Oguz.Data;
using Oguz.Areas;
using Oguz.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;

namespace Oguz.Controllers
{
    public class PillowsController : Controller
    {
        private readonly ApplicationDbContext _context;
        IWebHostEnvironment _appEnvironment;

        public PillowsController(ApplicationDbContext context, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _appEnvironment = appEnvironment;
        }

        // GET
        public IActionResult Index()
        {
            var pillow = _context.Pillows.Include(m => m.Brand).Include(c => c.Colors).ToList();
            if (pillow == null || pillow.Count == 0)
                return RedirectToAction(nameof(Create));
            return View(pillow);
        }

        // GET
        public IActionResult Create()
        {
            ViewBag.Brands = new SelectList(_context.Brands, "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Pillow pillow, IFormFile image)
        {
            if (image != null)
            {
                var path = FilesHelper.UploadFile(_appEnvironment.WebRootPath + "\\Images\\Pillows\\", image);
                pillow.ImageName = path.ToString();
            }
            if (ModelState.IsValid)
            {
                pillow.Id = Guid.NewGuid();
                //pillow.Category = Category.Pillows;
                //Size size = new Size
                //{
                //    Id = Guid.NewGuid(),
                //    Height = pillow.Size.Height,
                //    Width = pillow.Size.Width
                //};
                //_context.Add(pillow);
                //pillow.SizeId = size.Id;
                _context.Add(pillow);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }


        // GET
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pillow = await _context.Pillows.FindAsync(id);
            if (pillow == null)
            {
                return NotFound();
            }
            ViewData["BrandId"] = new SelectList(_context.Brands, "Id", "Name", pillow.BrandId);
            return View(pillow);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Pillow pillow, IFormFile image)
        {
            if (image != null)
            {
                string fileName = pillow.ImageName;
                string fullPath = _appEnvironment.ApplicationName + "\\Images\\Pillows\\" + pillow.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                var path = FilesHelper.UploadFile(_appEnvironment.WebRootPath + "\\Images\\Pillows\\", image);
                pillow.ImageName = path.ToString();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pillow);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PillowsExists(pillow.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pillow);
        }

        public IActionResult Delete(Guid? id)
        {
            var pillow = _context.Pillows.Find(id);
            var colors = _context.Colors.Where(c => c.ProductId == id);
            _context.Colors.RemoveRange(colors);
            foreach (var item in colors)
            {
                string ColorImagePath = _appEnvironment.ApplicationName + "\\Images\\Colors\\" + item.ImageName;
                if (System.IO.File.Exists(ColorImagePath))
                {
                    System.IO.File.Delete(ColorImagePath);
                }
            }
            string PillowImagePath = _appEnvironment.ApplicationName + "\\Images\\Pillows\\" + pillow.ImageName;
            if (System.IO.File.Exists(PillowImagePath))
            {
                System.IO.File.Delete(PillowImagePath);
            }
            _context.Pillows.Remove(pillow);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool PillowsExists(Guid id)
        {
            return _context.Pillows.Any(e => e.Id == id);
        }
    }
}

Oguz/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Oguz.Data;
using Oguz.Models;

namespace Oguz.Controllers
{
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<ApplicationUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index() => View(_userManager.Users.ToList());

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string userId)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);
                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index");
            }

            return NotFound();
        }
    }
}

Oguz/Views/Admin/Clients.cshtml
<div class="container-fluid" id="clientsList">
    <div class="container mt-4">
        <h2 class="mb-4">Список клиентов</h2>

        <div class="mt-4">
            <div id="clientsTabulator"></div>
        </div>
    </div>

</div>


<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
<script src="~/js/Admin/ClientsList.js"></script>

Oguz/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Panel";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="text-center">
    <h1>Diagrams</h1>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.js"></script>
<script src="~/js/DrawDiagrams.js"></script>

Oguz/Views/Admin/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oguz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Animation.css" />
</head>
<body>
    <div id="preloader">
        <div class="cssload-wrench"></div>
    </div>
    <header>
        <div class="bigDevice-header ">
            <div class="container d-flex justify-content-between align-items-center">
                <a class="nav-brand" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                <div class="nav-menu">
                    <ul class="d-flex">
                        <li class="nav-item">
                            <a class=" text-dark" asp-area="" asp-action="Orders">Заказы</a>
                        </li>
                        <li class="nav-item">
                            <a class=" text-dark" asp-area="" asp-action="Clients">Клиенты</a>
                        </li>
                        <li class="dropdown">
                            <a class=" text-dark" href="#">
                                 Данные
                                <span class="caret-down"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                            </a>
                            <div class="dropdown-menu" style="display: none">
                                <a class="dropdown-item" asp-controller="Curtains" asp-action="Index">Шторы</a>
                                <a class="dropdown-item" asp-controller="Pillows" asp-action="Index">Подушки</a>
                                @*<a class="dropdown-item" asp-controller="Accessories" asp-action="Index">Акссесуары</a>*@
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Brands" asp-action="Index">Бренды</a>

                            </div>
                        </li>
                        <li class="dropdown">
                            <a class=" text-dark" href="#">
                                 Настройки
                                <span class="caret-down"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                            </a>
                            <div class="dropdown-menu" style="display: none">
                                <a class="dropdown-item" asp-controller="SMTPClients">Почта</a>
                                <a class="dropdown-item" asp-controller="Roles">Роли</a>
                                <a class="dropdown-item" asp-controller="Discounts" asp-action="Index">Скидки</a>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="">
                    Посещений: 23
                </div>
            </div>
        </div>
        <div class="smallDevice-header">
            <nav class="navbar navbar-expand-sm navbar-toggleable-lg navbar-light mb-3 border-bottom box-shadow">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                    <div class="basket">
                        Посещений: 23
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav d-flex">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Образцы</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                    Данные
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Образцы</a>
                                    <a class="dropdown-item" href="#">Шторы</a>
                                    <a class="dropdown-item" href="#">Гардины</a>
                                    <a class="dropdown-item" href="#">Подушки</a>
                                    <a class="dropdown-item" href="#">Акссесуары</a>
                                </div>
                            </li>
                            <li class="dropdown">
                                <a class=" text-dark" href="#">
                                    Настройки
                                    <span class="caret-down"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                                </a>
                                <div class="dropdown-menu" style="display: none">
                                    <a class="dropdown-item" href="#">Почта</a>
                                    <a class="dropdown-item" href="#">Роли</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="subscribe">
            <div class="container text-center">
                <a asp-controller="Home" asp-action="Index"><h3>Вернуться на сайт</h3></a>
            </div>
        </div>
        <div class="container pt-4">
            <div class="row pb-4 d-flex justify-content-center">

                <div class="col">
                    <h3 class="pb-3 pt-2 pl-40px">Logo</h3>
                    &copy; 2020 - Oguz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
                <div class="col">

                    <h3 class="pb-3 pt-2">Магазин</h3>
                    <ul>
                        <li><a href="">Шторы</a></li>
                        <li><a href="">Гардины</a></li>
                        <li><a href="">Подушки</a></li>
                        <li><a href="">Акссесуары</a></li>
                    </ul>
                </div>
                <div class="col">
                    <h3 class="pb-3 pt-2 ">Бренды</h3>
                    <ul>
                        <li><a href="">Sarlas in Style</a></li>
                        <li><a href="">Casari design</a></li>
                    </ul>
                </div>
                <div class="col">

                    <h3 class="pb-3 pt-2">Контакты</h3>
                    <ul>
                        <li><a href="">email</a></li>
                        <li><a href="">Телефон</a></li>
                        <li><a href="">Адрес</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/preloader.js"></script>
    <script src="~/js/dropdown-menu.js"></script>
    <script src="~/js/Tabulator/tabulator.js"></script>
    <script src="~/js/Tabulator/tabulator.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
    
</body>
</html>