Oguz/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Oguz.Data;

namespace Oguz.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Clients()
        {
            return View();
        }

        public IEnumerable<ApplicationUser> GetAllClients()
        {
            return _context.ApplicationUsers;
        }
    }
}

Oguz/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Oguz.Data;

namespace Oguz.Controllers
{
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProfileController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Profile()
        {
            return View();
        }
    }
}

Oguz/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Oguz.Data;

namespace Oguz.Controllers
{
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShopController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Curtains()
        {
            return View();
        }
        public IActionResult Pillows()
        {
            return View();
        }
        public IActionResult CurtainsInfo(Guid id)
        {
            var result = _context.Curtains.FirstOrDefault(i => i.Id == id);
            return View(result);
        }
        public IActionResult PillowsInfo(Guid id)
        {
            var result = _context.Pillows.FirstOrDefault(u => u.Id == id);
            return View(result);
        }
    }
}

Oguz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oguz</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Animation.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    @*<link rel="stylesheet" href="~/css/zoomy0.5.css" />*@
    <link type="text/css" rel="stylesheet" href="~/css/zoomy0.5.css" />
    @*<script type="text/javascript" src="https://www.03www.ru/2013-04/88/jquery.zoomy0.5.js"></script>*@


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://www.03www.ru/2013-04/jquery.js"></script>
    <script src="~/js/site.js"></script>

    <script src="https://unpkg.com/vue@latest"></script>
    <link href="https://unpkg.com/tabulator-tables@4.4.1/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.4.1/dist/js/tabulator.min.js"></script>
    <script src="https://unpkg.com/vue-tabulator@latest"></script>
</head>
<body>
    <div id="preloader">
        <div class="cssload-wrench"></div>
    </div>
    <header>
        <div class="bigDevice-header">
            <nav class="navbar">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="nav-brand" asp-area="" asp-controller="Admin" asp-action="Index">Oguz</a>
                    </div>
                    <ul class="nav navbar-center">
                        <li class="nav-item">
                            <a class=" text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="dropdown">
                            <a class=" text-dark" href="#">
                                Купить
                                <span class="caret-down"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                            </a>
                            <div class="dropdown-menu" style="display: none">
                                <a class="dropdown-item" asp-controller="Shop" asp-action="Curtains">Шторы</a>
                                @*<a class="dropdown-item" asp-controller="OrderCurtains" asp-action="Index" asp-category="@Category.Shades">Гардины</a>*@
                                <a class="dropdown-item" asp-controller="Shop" asp-action="Pillows">Подушки</a>
                                @*<a class="dropdown-item" asp-controller="" asp-action="Index" asp-category="@Category.Accessories">Акссесуары</a>*@
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                        </li>
                    </ul>

                    <ul class="nav  navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="dropdown  navbar-right">
                                <a class=" text-dark" asp-controller="Profile" asp-action="Profile">
                                    @User.Identity.Name
                                    <span class="caret-down"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                                </a>
                                <div class="dropdown-menu" style="display: none">
                                    <a class="dropdown-item" asp-controller="Profile" asp-action="Profile">Профиль</a>
                                    <a class="dropdown-item" asp-controller="Profile" asp-action="Orders" asp-category="@Category.Pillows">Мои заказы</a>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="Logout" asp-category="@Category.Accessories">Выйти</a>
                                </div>
                            </li>
                        }
                        else
                        {
                            <li>
                                <div class="mb-0 row align-items-center">
                                    <div>
                                        <a asp-controller="Account" asp-action="Login">
                                            <input type="button" value="Войти" />
                                        </a>
                                    </div>
                                </div>
                            </li>
                        }
                        @*<li class="navbar-right">
                            <div class="basket pl-3">
                                <a href="/" class="basket-icon">
                                    <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
                                    <span id="basket-count">0</span>
                                </a>
                                <div id="basket-sum">$0.00</div>
                            </div>
                        </li>
                        <li class="dropdown">
                            <a class="text-dark" asp-controller="Profile" asp-action="Profile" style="margin-left:15px">
                                Мой профиль
                                <span class="caret-down"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                            </a>
                            <div class="dropdown-menu" style="display: none">
                                <a class="dropdown-item" asp-controller="" asp-action="">Данные</a>
                                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">Заказы</a>
                                <a class="dropdown-item" asp-controller="Discounts" asp-action="DiscountExists">Мои скидки</a>
                                <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Выйти</a>
                            </div>
                        </li>*@
                    </ul>
                </div>
            </nav>
        </div>
        <div class="smallDevice-header">
            <nav class="navbar navbar-expand-sm navbar-toggleable-lg navbar-light mb-3 border-bottom box-shadow">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Oguz</a>
                    <div class="basket">
                        <a href="/" class="basket-icon">
                            <i class="fa fa-shopping-cart fa-2x" aria-hidden="true"></i>
                            <span id="basket-count">0</span>
                        </a>
                        <div id="basket-sum">$0.00</div>
                    </div>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav d-flex">
                            <li class="nav-item dropdown">
                                <a class="nav-link text-dark dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                                    Купить
                                </a>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                            </li>
                            <li>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="CurtainsOrder" asp-action="Index" asp-category="@Category.Curtains">Шторы</a>
                                    <a class="dropdown-item" asp-controller="CurtainsOrder" asp-action="Index" asp-category="@Category.Shades">Гардины</a>
                                    <a class="dropdown-item" asp-controller="" asp-action="Index" asp-category="@Category.Pillows">Подушки</a>
                                    <a class="dropdown-item" asp-controller="" asp-action="Index" asp-category="@Category.Accessories">Акссесуары</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="container-fluid">
            @RenderBody()
        </div>
    </header>

    <footer class="footer text-muted">
        @*<div class="subscribe">
            <div class="container text-center">
                <h2>Подпишись</h2>
                <div class="wrap-normal">Просто введи email чтобы получать уведомления о новых коллекциях и распродажах</div>
                <br />
                <div class="row mr-0 ml-0" style="display:block">
                    <input id="Subscribe" type="email" class="contact_email" name="contact[email]" required="" placeholder="Enter your email address...">
                    <input id="SubscribeButton" type="submit" class="action_button sign_up btn" value="ОК">
                </div>
            </div>
        </div>*@
        <div class="container pt-4">
            <div class="row pb-4 d-flex justify-content-center">

                <div class="col">
                    <h3 class="pb-3 pt-2 pl-40px">Logo</h3>
                    &copy; 2020 - Oguz - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
                <div class="col">

                    <h3 class="pb-3 pt-2">Магазин</h3>
                    <ul>
                        <li><a href="">Шторы</a></li>
                        <li><a href="">Гардины</a></li>
                        <li><a href="">Подушки</a></li>
                        <li><a href="">Акссесуары</a></li>
                    </ul>
                </div>
                <div class="col">
                    <h3 class="pb-3 pt-2 ">Бренды</h3>
                    <ul>
                        <li><a href="">Sarlas in Style</a></li>
                        <li><a href="">Casari design</a></li>
                    </ul>
                </div>
                <div class="col">

                    <h3 class="pb-3 pt-2">Контакты</h3>
                    <ul>
                        <li><a href="">email</a></li>
                        <li><a href="">Телефон</a></li>
                        <li><a href="">Адрес</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/preloader.js"></script>
    <script src="~/js/Subscribe.js"></script>
    <script src="~/js/dropdown-menu.js"></script>
    <script src="~/js/orderProgressBar.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>